### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jblernout** [nhachicha/SnappyDB#20]
Here is the error I obtain on some devices like Galaxy S4, note 2, xperia M...

java.lang.UnsatisfiedLinkError: Couldn't load snappydb-native from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.jbl.android.spotimote-4.apk,libraryPath=/data/app-lib/com.jbl.android.spotimote-4]: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:358)
at java.lang.System.loadLibrary(System.java:526)
at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:38)
at com.snappydb.DBFactory.open(DBFactory.java:40)
at com.snappydb.DBFactory.open(DBFactory.java:65)
at com.snappydb.DBFactory.open(DBFactory.java:77)
at com.jbl.android.spotimote.Lookup.ItemsCache.<init>(ItemsCache.java:31)
at com.jbl.android.spotimote.SpotimoteService.bootService(SpotimoteService.java:319)
at com.jbl.android.spotimote.SpotimoteService.onStartCommand(SpotimoteService.java:230)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2860)
at android.app.ActivityThread.access$2200(ActivityThread.java:161)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5356)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)

**Comment by iKiKi** [comment]
Same runtime error when I try to run my Android app on HTC Nexus 9 (API 21)

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.my.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.my.app-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsnappydb-native.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:38)
            at com.snappydb.DBFactory.open(DBFactory.java:40)
            at com.snappydb.DBFactory.open(DBFactory.java:65)
            ...
```

**Comment by iKiKi** [comment]
0.5.0 release provide : 
* armeabi-v7a
* armeabi
* x86
* mips

Following libs are missing : 
* arm64-v8a
* x86_64
* mips64

**Comment by iKiKi** [comment]
@nhachicha : It seems that you use the [32bits NDK](http://dl.google.com/android/ndk/android-ndk-r10d-darwin-x86.bin) to build your library.
I tried to build SnappyDB using the  [32/64bits NDK](http://dl.google.com/android/ndk/android-ndk-r10d-darwin-x86_64.bin) but I encounter the following error:
```
[arm64-v8a] Compile++      : snappydb-native <= port_android.cc
jni/./port/port_android.cc: In function 'int fdatasync(int)':
jni/./port/port_android.cc:23:18: error: 'fsync' was not declared in this scope
   return fsync(fd);
                  ^
```

**Comment by edcheezburger** [comment]
Getting the same issue on an HTC One X, which I don't believe is 64 bit:

Caused by: java.lang.UnsatisfiedLinkError: Couldn't load snappydb-native: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:365)
       at java.lang.System.loadLibrary(System.java:535)
       at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:40)

**Comment by pueding** [comment]
Is there anyone trying to fix this?

**Comment by nhachicha** [comment]
Hi
32 bits native libs should run without a problem on 64bits 

did you use the `AAR` to import the lib?
what's the output of `jar -tf your.apk`?
can you share pls code/apk so I can investigate 

Cheers

**Comment by nhachicha** [comment]
Hi,
I pushed a snapshot `AAR` including `64-bit ABIs` can you please check if it works. I'll push to maven central ASAP.
```groovy
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
    compile 'com.snappydb:snappydb-lib:0.5.1-SNAPSHOT'
    compile 'com.esotericsoftware.kryo:kryo:2.24.0'
}
````
Cheers,

**Comment by frostymarvelous** [comment]
I just faced this issue on an XPeria T (related closely to the M). Uninstalling and installing seems to have fixed it.

**Comment by van11** [comment]
Hi,
we are still facing issues, stacktrace: 
```
Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load snappydb-native from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/X-2.apk", zip file "/data/data/X/code_cache/secondary-dexes/X-2.apk.classes2.zip"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:355)
       at java.lang.System.loadLibrary(System.java:525)
       at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:40)
       at com.snappydb.DBFactory.open(DBFactory.java:40)
       at com.snappydb.DBFactory.open(DBFactory.java:65)
       at com.snappydb.DBFactory.open(DBFactory.java:77)
```
snappy db version: `com.snappydb:snappydb-lib:0.5.2`

Any tips how to avoid this would be helpful :)

Thanks.

**Comment by viadanna** [comment]
Hello guys,

I started seeing this issue today after updating play-services to 8.3.0. Downgrading back to 8.1.0 works for now.
```
classpath 'com.google.gms:google-services:1.4.0-beta3'
compile 'com.google.android.gms:play-services:8.1.0'
```

**Comment by wondertwo** [comment]
i have the same error on my device OnePlus 7 Pro, error like

```
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[...] couldn't find "libsnappydb-native.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:38)
        at com.snappydb.DBFactory.open(DBFactory.java:40)
        at com.snappydb.DBFactory.open(DBFactory.java:65)
        ......
```

**Comment by wondertwo** [comment]
> Hi,
> I pushed a snapshot `AAR` including `64-bit ABIs` can you please check if it works. I'll push to maven central ASAP.
> 
> ```groovy
> repositories {
>     maven {
>         url "https://oss.sonatype.org/content/repositories/snapshots"
>     }
> }
> 
> dependencies {
>     compile 'com.snappydb:snappydb-lib:0.5.1-SNAPSHOT'
>     compile 'com.esotericsoftware.kryo:kryo:2.24.0'
> }
> ```
> 
> Cheers,

it works for my error
